on:
  push:
  workflow_dispatch:

name: All ubuntu build and test

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    container:
      image: ${{ matrix.config.container }}
      options: --user ${{matrix.config.user}}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: macOS-latest,   r: 'release'}
          #- {os: windows-latest, r: 'release'}
          - {type: 'test', os: 'ubuntu-latest', container: 'ghcr.io/bioconductor/bioconductor_salt:22.04-bioc-3.18', user: 'root'}
          - {type: 'binary-build', os: 'ubuntu-latest', container: 'bioconductor/bioconductor:3.18', user: 'root'}
          - {type: 'deb-build', os: 'ubuntu-latest', container: 'ghcr.io/bioconductor/bioc2u-builder:jammy-bioc-3.18-r-4.3.2', user: 'root'}
    steps:
      - uses: actions/checkout@v4

      - id: common
        run: |
          df -lh
